services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql-dev
        ports:
            - "15432:1433"
        environment:
            SA_PASSWORD: "YourStrong!Passw0rd"
            ACCEPT_EULA: "Y"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
            interval: 10s
            timeout: 3s
            retries: 10
        command: /opt/mssql/bin/sqlservr

    servlet:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: servlet-app
        ports:
            - "8080:8080"
        depends_on:
            mssql:
                condition: service_healthy

    sqlcmd:
        image: mcr.microsoft.com/mssql-tools
        depends_on:
            - mssql
        entrypoint: >
            /bin/bash -c "
            sleep 20 &&
            /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P 'YourStrong!Passw0rd' -i /init.sql
            "
        volumes:
            - ./database/init.sql:/init.sql
        networks:
            - default
