version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-dev
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 20 &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -i /docker-entrypoint-initdb.d/init.sql &&
      tail -f /dev/null
      "

  servlet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servlet-app
    ports:
      - "8080:8080"
    depends_on:
      - mssql
